services:

  api:
    build:
      context: ./src/api
    container_name: api
    environment:
      - SQL_CONNECTION=Server=db;UID=sa;PWD=${MSSQL_SA_PASSWORD};trusted_connection=false;Persist Security Info=False;Encrypt=False;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8000:80
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: /healthchecks/curl.sh
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_completed_successfully

  app:
    build:
      context: ./src/app
    container_name: app
    environment:
      - SQL_CONNECTION=Server=db;UID=sa;PWD=${MSSQL_SA_PASSWORD};trusted_connection=false;Persist Security Info=False;Encrypt=False;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy
