services:

  app:
    build:
      context: app
      args:
        - BUILDPLATFORM=linux/amd64 # linux/arm64/v8
        - TARGETARCH=x86
    container_name: app
    environment:
      - DB_SERVER=db
      - DB_USER=sa
      - DB_PWD=${MSSQL_SA_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  ## 1) Bootstrap with scripts
  db:
    build: ./docker/db
    pull_policy: missing
    container_name: db
    hostname: db
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -b
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  ## 2) Restore db from backup
  backup:
    build: ./docker/backup
    #restart: 'no' #unless-stopped
    container_name: backup
    hostname: backup
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
       - 1403:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -b
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
